site_name: Estrutura de projeto
nav:
  - Home: index.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python

repo_name: "estrutura_de_projeto"
repo_url: "https://github.com/heitorfe/estrutura_de_projeto"